{
  "version": "3",
  "services": {
    "dash": {
      "build": {
        "context": ".",
        "args": [
          "NODE_ENV=dev"
        ]
      },
      "command": [
        "npm",
        "run",
        "dev"
      ],
      "volumes": [
        "./k8s_files:/var/run/secrets/kubernetes.io/serviceaccount",
        "./config.json:/dash/config.json"
      ],
      "env_file": "env.variables",
      "ports": [
        "8080:3000"
      ],
      "develop": {
        "watch": [
          {
            "path": "./backend",
            "action": "rebuild"
          },
          {
            "path": "./frontend",
            "action": "rebuild"
          }
        ]
      }
    }
  }
}